#!/usr/bin/env ruby

posts_dir       = "_posts/#{Time.now.strftime('%Y')}"
puts posts_dir
new_post_ext    = "md"

title = ARGV.first
if title && title.length
else 
puts title.class 
  def get_stdin(message)
    print message
    STDIN.gets.chomp
  end
  title = get_stdin "输入文章标题:"
end 


if title == nil || title.length == 0
    puts "exit"
    exit 1
end 
    
begin
    Dir.mkdir "#{posts_dir}"
rescue => exception
    
end
  
  filename = "#{posts_dir}/#{Time.now.strftime('%Y-%m-%d')}-#{title.to_s}.#{new_post_ext}"
  puts filename
  Dir::mkdir "pics/#{Time.now.strftime('%Y-%m-%d')}-#{title.to_s}"
  if File.exist?(filename)
    abort("rake aborted!") if ask("#{filename} already exists. Do you want to overwrite?", ['y', 'n']) == 'n'
  end
  puts "Creating new post: #{filename}"
  open(filename, 'w') do |post|

    post.puts "---"
    post.puts "layout: post"
    post.puts "title: \"#{title}\""
    post.puts "date: \"#{Time.now.strftime('%Y-%m-%d %H:%M:%S')}\""
    post.puts "categories: "
    post.puts " - 流水账 "
    post.puts "mathjax: false "
    post.puts "# key: false "
    post.puts "tags:"
    post.puts " - 流水账"
    post.puts " - 日常"
    post.puts "---"
  end



def get_stdin(message)
  print message
  STDIN.gets.chomp
end

def ask(message, valid_options)
  if valid_options
    answer = get_stdin("#{message} #{valid_options.to_s.gsub(/"/, '').gsub(/, /,'/')} ") while !valid_options.include?(answer)
  else
    answer = get_stdin(message)
  end
  answer
end